### ISSUE TITLE
Add Netlify deployment pipeline support

### ISSUE THREAD

**Issue by hectcastro** [PublicMapping/publicmapping.github.com#3]
- Configure the site with Netlify
- Add a `netlify.toml` file that properly executes the Jekyll build process

```toml
[Settings]
  ID = "..."

[build]
  base    = "."
  publish = "_site"
  command = "jekyll build"

[context.production]
  environment = { JEKYLL_ENV = "production" }
```
